package kz.pandev.legrambotapi.models.requests.chat.invite.link;

import kz.pandev.legrambotapi.exceptions.WrongParameterTypeException;
import kz.pandev.legrambotapi.models.requests.Request;
import kz.pandev.legrambotapi.models.responses.StringResponse;
import org.jetbrains.annotations.NotNull;

/**
 * Use this method to generate a new primary invite link for a chat; any previously generated
 * primary link is revoked. The bot must be an administrator in the chat for this to work and
 * must have the appropriate administrator rights. Returns the new invite link as String on success.
 * @apiNote Each administrator in a chat generates their own invite links. Bots can't use invite links
 * generated by other administrators. If you want your bot to work with invite links, it will need to
 * generate its own link using exportChatInviteLink or by calling the getChat method. If your bot needs
 * to generate a new primary invite link replacing its previous one, use exportChatInviteLink again.
 * @author ezuykow
 */
public class ExportChatInviteLink extends Request<ExportChatInviteLink, StringResponse> {

    /**
     * @param chatId Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     */
    public ExportChatInviteLink(@NotNull Object chatId) {
        super(StringResponse.class);
        if (chatId instanceof Number || chatId instanceof String) {
            addParameter("chat_id", chatId);
        } else {
            throw new WrongParameterTypeException("Type of parameter chatId must be Number or String (if it's chat username)");
        }
    }
}